spring.application.name=uuid-as-a-service

# H2 In-Memory Database (Enterprise-Grade Storage)
spring.datasource.url=jdbc:postgresql://db.example.com:5432/uuiddb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=sa
spring.datasource.password=RGJTZWNyZXQyMDI2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Server
server.port=8080

# Actuator (because we're enterprise)
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
