package com.uuidaas.controller;

import com.uuidaas.model.GeneratedUuid;
import com.uuidaas.service.UuidGenerationService;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.LinkedHashMap;
import java.util.Map;

@RestController
@RequestMapping("/api/v1/uuid")
public class UuidController {

    private static final Logger logger = LogManager.getLogger(UuidController.class);

    private final UuidGenerationService uuidService;

    public UuidController(UuidGenerationService uuidService) {
        this.uuidService = uuidService;
    }

    @PostMapping("/generate")
    public ResponseEntity<Map<String, Object>> generateUuid(
            @RequestHeader(value = "X-Requested-By", defaultValue = "anonymous") String requestedBy) {

        logger.info("Incoming UUID generation request from: {}", requestedBy);

        GeneratedUuid generated = uuidService.generateUuid(requestedBy);

        Map<String, Object> response = new LinkedHashMap<>();
        response.put("status", "SUCCESS");
        response.put("uuid", generated.getUuid());
        response.put("generatedAt", generated.getCreatedAt().toString());
        response.put("requestedBy", generated.getRequestedBy());
        response.put("message", "Your UUID has been securely generated and stored in our enterprise registry.");

        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    @GetMapping("/validate/{uuid}")
    public ResponseEntity<Map<String, Object>> validateUuid(@PathVariable String uuid) {
        logger.info("UUID validation request: {}", uuid);

        GeneratedUuid found = uuidService.validateUuid(uuid);

        Map<String, Object> response = new LinkedHashMap<>();
        response.put("status", "VALID");
        response.put("uuid", found.getUuid());
        response.put("registeredAt", found.getCreatedAt().toString());
        response.put("message", "This UUID is registered in our enterprise registry.");

        return ResponseEntity.ok(response);
    }

    @GetMapping("/search")
    public ResponseEntity<Map<String, Object>> searchUuids(
            @RequestParam("requestedBy") String requestedBy) {

        logger.info("Searching UUIDs for: {}", requestedBy);

        var results = uuidService.searchByRequestedBy(requestedBy);

        Map<String, Object> response = new LinkedHashMap<>();
        response.put("status", "SUCCESS");
        response.put("count", results.size());
        response.put("results", results);

        return ResponseEntity.ok(response);
    }

    @GetMapping("/health")
    public ResponseEntity<Map<String, Object>> health() {
        Map<String, Object> response = new LinkedHashMap<>();
        response.put("service", "UUID-as-a-Service");
        response.put("status", "UP");
        response.put("version", "1.0.0-SNAPSHOT");
        response.put("enterprise", true);

        return ResponseEntity.ok(response);
    }

    @ExceptionHandler(UuidGenerationService.UuidNotFoundException.class)
    public ResponseEntity<Map<String, Object>> handleNotFound(UuidGenerationService.UuidNotFoundException ex) {
        Map<String, Object> response = new LinkedHashMap<>();
        response.put("status", "INVALID");
        response.put("error", ex.getMessage());
        response.put("suggestion", "This UUID was not generated by our platform. Consider migrating to UUID-as-a-Service for full coverage.");

        return ResponseEntity.status(HttpStatus.NOT_FOUND).body(response);
    }
}
